package com.company.projetlo54.entity;
// Generated 29 oct. 2016 16:40:13 by Hibernate Tools 4.3.1


import com.mycompany.projetlo54.entity.CourseSession;
import javax.persistence.*;




/**
 * Client generated by hbm2java
 */
@Entity
public class Client  implements java.io.Serializable {

@Id
@GeneratedValue()
     private int id;
@Column( name="COURSE_SESSION_ID" )
     private CourseSession courseSession;
@Column(name ="LASTNAME")
     private String lastname;
@Column( name="FIRSTNAME")
     private String firstname;
@Column(name="ADDRESS")
     private String address;
@Column(name ="PHONE")
     private String phone;
@Column(name="EMAIL")
     private String email;

    public Client() {
    }

    public Client(int id, CourseSession courseSession, String lastname, String firstname, String address, String phone, String email) {
       this.id = id;
       this.courseSession = courseSession;
       this.lastname = lastname;
       this.firstname = firstname;
       this.address = address;
       this.phone = phone;
       this.email = email;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public CourseSession getCourseSession() {
        return this.courseSession;
    }
    
    public void setCourseSession(CourseSession courseSession) {
        this.courseSession = courseSession;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


