package com.company.projetlo54.entity;
// Generated 29 oct. 2016 16:40:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private String code;
     private String title;
     private Set<CourseSession> courseSessions = new HashSet<CourseSession>(0);

    public Course() {
    }

	
    public Course(String code) {
        this.code = code;
    }
    public Course(String code, String title, Set<CourseSession> courseSessions) {
       this.code = code;
       this.title = title;
       this.courseSessions = courseSessions;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Set<CourseSession> getCourseSessions() {
        return this.courseSessions;
    }
    
    public void setCourseSessions(Set<CourseSession> courseSessions) {
        this.courseSessions = courseSessions;
    }




}


