package com.company.projetlo54.entity;
// Generated 29 oct. 2016 16:40:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Location generated by hbm2java
 */
public class Location  implements java.io.Serializable {


     private int id;
     private String city;
     private Set<CourseSession> courseSessions = new HashSet<CourseSession>(0);

    public Location() {
    }

	
    public Location(int id, String city) {
        this.id = id;
        this.city = city;
    }
    public Location(int id, String city, Set<CourseSession> courseSessions) {
       this.id = id;
       this.city = city;
       this.courseSessions = courseSessions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Set<CourseSession> getCourseSessions() {
        return this.courseSessions;
    }
    
    public void setCourseSessions(Set<CourseSession> courseSessions) {
        this.courseSessions = courseSessions;
    }




}


